booking_df <- read_csv("hotel_bookings.csv")
head(booking_df)
str(booking_df)
glimpse(booking_df)
colnames(booking_df)
skim_without_charts(booking_df)
trimmed_df <- booking_df %>% select ("hotel", "is_canceled", "lead_time")
arrange(booking_df, desc(lead_time))
str(booking_df)
arrange(booking_df, -(lead_time))